version: '3.0'

services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - RUST_LOG=info
      - ROCKET_ENV=production
    command: cargo run
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local