[development]
address = "127.0.0.1"
port = 8000
workers = 4
keep_alive = 10
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 15
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 16
keep_alive = 20
log = "critical"
limits = { forms = 32768 }